# Generated by Django 6.0 on 2025-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productsize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='requires_size',
            field=models.BooleanField(default=False, verbose_name='Need a size'),
        ),
    ]
