# Generated by Django 5.2.9 on 2026-01-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
