# Generated by Django 5.2.9 on 2026-01-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_rating_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity in warehouse'),
        ),
    ]
