# Generated by Django 6.0 on 2025-12-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('main', '0002_alter_productsize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productsize'),
        ),
    ]
