# Generated by Django 5.2.9 on 2026-01-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вхід в систему'), ('logout', 'Вихід з системи'), ('register', 'Реєстрація'), ('password_change', 'Зміна паролю'), ('product_create', 'Створення товару'), ('product_update', 'Оновлення товару'), ('product_delete', 'Видалення товару'), ('product_view', 'Перегляд товару'), ('cart_add', 'Додавання в кошик'), ('cart_update', 'Оновлення кошика'), ('cart_remove', 'Видалення з кошика'), ('cart_clear', 'Очищення кошика'), ('order_create', 'Створення замовлення'), ('order_update', 'Оновлення замовлення'), ('order_cancel', 'Скасування замовлення'), ('review_create', 'Створення відгуку'), ('review_update', 'Оновлення відгуку'), ('review_delete', 'Видалення відгуку'), ('profile_update', 'Оновлення профілю'), ('other', 'Інша дія')], max_length=50, verbose_name='Action type')),
                ('description', models.TextField(blank=True, verbose_name='Action description')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Object type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Object representation')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Additional information')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_success', models.BooleanField(default=True, verbose_name='Successfully')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of action')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='logs_action_user_id_0bd72f_idx'), models.Index(fields=['action_type', '-created_at'], name='logs_action_action__e2c8f5_idx'), models.Index(fields=['-created_at'], name='logs_action_created_df0cfe_idx')],
            },
        ),
    ]
